"""Language-model evaluation (v0.4.0): text generation, semantic similarity, factuality and hallucination,
LLM-as-a-judge and preferences, reasoning benchmarks, retrieval-augmented generation, and instruction following
and structured output."""

from .factuality import (
    abstention_accuracy,
    answer_correctness,
    answer_relevance,
    citation_precision,
    citation_recall,
    claim_verification_accuracy,
    faithfulness,
    groundedness,
    hallucination_rate,
    knowledge_consistency,
)
from .generation import (
    bleu,
    chrf,
    cider,
    cross_entropy,
    distinct_n,
    meteor,
    perplexity,
    rouge_1,
    rouge_2,
    rouge_l,
    rouge_lsum,
    self_bleu,
    sentence_bleu,
    ter,
)
from .judge import (
    bradley_terry,
    elo_ratings,
    fleiss_kappa,
    judge_agreement,
    krippendorff_alpha,
    position_consistency,
    rubric_score,
    self_preference_bias,
    verbosity_bias,
    win_rate,
)
from .qa import exact_match, normalize_answer, token_f1
from .rag import (
    context_precision,
    context_recall,
    context_relevance,
    failure_attribution,
    latency_summary,
    task_success_rate,
)
from .reasoning import benchmark_accuracy, extract_answer, majority_vote_accuracy, pass_at_k
from .report import TextReport, text_report
from .retrieval import hit_rate_at_k, mean_average_precision_at_k, mrr, ndcg_at_k, precision_at_k, recall_at_k
from .semantic import bertscore, embedding_similarity, mauve, model_score, moverscore
from .spice import spice
from .structured import (
    api_call_success_rate,
    constraint_satisfaction_rate,
    extra_content_rate,
    extract_json,
    format_compliance,
    instruction_compliance_rate,
    instruction_retention,
    json_schema_compliance,
    json_validity,
    required_field_accuracy,
    tool_argument_accuracy,
    tool_call_f1,
    tool_selection_accuracy,
    validate_json_schema,
    xml_validity,
)

__all__ = [
    "TextReport",
    "text_report",
    "abstention_accuracy",
    "answer_correctness",
    "answer_relevance",
    "api_call_success_rate",
    "benchmark_accuracy",
    "bertscore",
    "bleu",
    "bradley_terry",
    "chrf",
    "cider",
    "citation_precision",
    "citation_recall",
    "claim_verification_accuracy",
    "constraint_satisfaction_rate",
    "context_precision",
    "context_recall",
    "context_relevance",
    "cross_entropy",
    "distinct_n",
    "elo_ratings",
    "embedding_similarity",
    "exact_match",
    "extra_content_rate",
    "extract_answer",
    "extract_json",
    "failure_attribution",
    "faithfulness",
    "fleiss_kappa",
    "format_compliance",
    "groundedness",
    "hallucination_rate",
    "hit_rate_at_k",
    "instruction_compliance_rate",
    "instruction_retention",
    "json_schema_compliance",
    "json_validity",
    "judge_agreement",
    "knowledge_consistency",
    "krippendorff_alpha",
    "latency_summary",
    "majority_vote_accuracy",
    "mauve",
    "mean_average_precision_at_k",
    "meteor",
    "model_score",
    "moverscore",
    "mrr",
    "ndcg_at_k",
    "normalize_answer",
    "pass_at_k",
    "perplexity",
    "position_consistency",
    "precision_at_k",
    "recall_at_k",
    "required_field_accuracy",
    "rouge_1",
    "rouge_2",
    "rouge_l",
    "rouge_lsum",
    "rubric_score",
    "self_bleu",
    "self_preference_bias",
    "sentence_bleu",
    "spice",
    "task_success_rate",
    "ter",
    "token_f1",
    "tool_argument_accuracy",
    "tool_call_f1",
    "tool_selection_accuracy",
    "validate_json_schema",
    "verbosity_bias",
    "win_rate",
    "xml_validity",
]
