"""EvalSuite: unified, reproducible evaluation for machine learning and research.

>>> import evalsuite as es
>>> result = es.evaluate([0, 1, 1, 0], [0, 1, 0, 0])
>>> print(result.summary())  # doctest: +SKIP
"""

from . import calibration, classification, clinical, llmsys, plot, regression, stats, text, vision
from .api import evaluate
from .calibration import (
    CalibrationReport,
    calibration_intercept,
    calibration_report,
    calibration_slope,
    hosmer_lemeshow,
    maximum_calibration_error,
)
from .classification import (
    accuracy,
    average_precision,
    balanced_accuracy,
    brier_score,
    calibration_curve,
    cohen_kappa,
    confusion_matrix,
    expected_calibration_error,
    f1,
    fbeta,
    hamming_loss,
    jaccard,
    log_loss,
    mcc,
    npv,
    pr_curve,
    precision,
    recall,
    roc_auc,
    roc_curve,
    specificity,
    top_k_accuracy,
)
from .clinical import (
    DecisionCurve,
    DiagnosticReport,
    decision_curve,
    diagnostic_odds_ratio,
    diagnostic_report,
    lr_negative,
    lr_positive,
    net_benefit,
    ppv,
    sensitivity,
    youden_j,
)
from .core.exceptions import (
    EvalSuiteError,
    InputValidationError,
    MetricInputError,
    OptionalDependencyError,
    StatisticalTestError,
    UndefinedMetricWarning,
    UnsupportedTaskError,
)
from .core.registry import MetricInfo, list_metrics, metric_info
from .core.result import EvaluationResult, MetricResult
from .llmsys import *  # noqa: F403  (v0.5.0 LLM-systems functions, listed in llmsys.__all__)
from .llmsys import __all__ as _llmsys_all
from .regression import (
    adjusted_r2,
    explained_variance,
    huber_loss,
    mae,
    mape,
    max_error,
    mean_bias_error,
    median_absolute_error,
    mse,
    msle,
    quantile_loss,
    r2,
    rae,
    rmse,
    rmsle,
    rse,
    smape,
)
from .reporting import ClassificationReport, classification_report
from .stats import (
    ComparisonResult,
    ConfidenceInterval,
    TestResult,
    accuracy_ci,
    adjust_pvalues,
    bootstrap_ci,
    chi_square_test,
    cliffs_delta,
    cohens_d,
    compare,
    cramers_v,
    delong_test,
    fisher_exact_test,
    friedman_test,
    hedges_g,
    kruskal_wallis_test,
    mann_whitney_test,
    mcnemar_test,
    paired_bootstrap_test,
    paired_t_test,
    proportion_ci,
    roc_auc_ci,
    shapiro_wilk_test,
    t_test,
    wilcoxon_test,
)
from .text import *  # noqa: F403  (every LLM-evaluation function, listed in text.__all__)
from .text import __all__ as _text_all
from .version import __version__
from .vision import (
    DetectionReport,
    SegmentationReport,
    average_precision_detection,
    average_surface_distance,
    boundary_iou,
    box_iou,
    detection_pr_curve,
    detection_report,
    dice,
    from_coco,
    hausdorff_distance,
    iou,
    mean_average_precision,
    mean_pixel_accuracy,
    miou,
    per_image_scores,
    pixel_accuracy,
    segmentation_confusion,
    segmentation_report,
)

__all__ = [
    "text",
    "llmsys",
    "SegmentationReport",
    "segmentation_report",
    "detection_pr_curve",
    "vision",
    "DetectionReport",
    "average_precision_detection",
    "average_surface_distance",
    "boundary_iou",
    "box_iou",
    "detection_report",
    "dice",
    "from_coco",
    "hausdorff_distance",
    "iou",
    "mean_average_precision",
    "mean_pixel_accuracy",
    "miou",
    "per_image_scores",
    "pixel_accuracy",
    "segmentation_confusion",
    "CalibrationReport",
    "calibration_report",
    "calibration",
    "clinical",
    "calibration_intercept",
    "calibration_slope",
    "hosmer_lemeshow",
    "maximum_calibration_error",
    "DecisionCurve",
    "DiagnosticReport",
    "decision_curve",
    "diagnostic_odds_ratio",
    "diagnostic_report",
    "lr_negative",
    "lr_positive",
    "net_benefit",
    "ppv",
    "sensitivity",
    "youden_j",
    "chi_square_test",
    "cramers_v",
    "fisher_exact_test",
    "friedman_test",
    "kruskal_wallis_test",
    "mann_whitney_test",
    "paired_t_test",
    "shapiro_wilk_test",
    "t_test",
    "wilcoxon_test",
    "plot",
    "expected_calibration_error",
    "calibration_curve",
    "classification_report",
    "ClassificationReport",
    "stats",
    "roc_auc_ci",
    "proportion_ci",
    "paired_bootstrap_test",
    "mcnemar_test",
    "hedges_g",
    "delong_test",
    "compare",
    "cohens_d",
    "cliffs_delta",
    "bootstrap_ci",
    "adjust_pvalues",
    "accuracy_ci",
    "TestResult",
    "ConfidenceInterval",
    "ComparisonResult",
    "EvalSuiteError",
    "EvaluationResult",
    "InputValidationError",
    "MetricInfo",
    "MetricInputError",
    "MetricResult",
    "OptionalDependencyError",
    "StatisticalTestError",
    "UndefinedMetricWarning",
    "UnsupportedTaskError",
    "__version__",
    "accuracy",
    "adjusted_r2",
    "average_precision",
    "balanced_accuracy",
    "brier_score",
    "classification",
    "cohen_kappa",
    "confusion_matrix",
    "evaluate",
    "explained_variance",
    "f1",
    "fbeta",
    "hamming_loss",
    "huber_loss",
    "jaccard",
    "list_metrics",
    "log_loss",
    "mae",
    "mape",
    "max_error",
    "mcc",
    "mean_bias_error",
    "median_absolute_error",
    "metric_info",
    "mse",
    "msle",
    "npv",
    "pr_curve",
    "precision",
    "quantile_loss",
    "r2",
    "rae",
    "recall",
    "regression",
    "rmse",
    "rmsle",
    "roc_auc",
    "roc_curve",
    "rse",
    "smape",
    "specificity",
    "top_k_accuracy",
]
__all__ += list(_text_all)
__all__ += list(_llmsys_all)
