"""EvalSuite: unified, reproducible evaluation for machine learning and research.

>>> import evalsuite as es
>>> result = es.evaluate([0, 1, 1, 0], [0, 1, 0, 0])
>>> print(result.summary())  # doctest: +SKIP
"""

from . import classification, regression
from .api import evaluate
from .classification import (
    accuracy,
    average_precision,
    balanced_accuracy,
    brier_score,
    cohen_kappa,
    confusion_matrix,
    f1,
    fbeta,
    hamming_loss,
    jaccard,
    log_loss,
    mcc,
    npv,
    pr_curve,
    precision,
    recall,
    roc_auc,
    roc_curve,
    specificity,
    top_k_accuracy,
)
from .core.exceptions import (
    EvalSuiteError,
    InputValidationError,
    MetricInputError,
    OptionalDependencyError,
    StatisticalTestError,
    UndefinedMetricWarning,
    UnsupportedTaskError,
)
from .core.registry import MetricInfo, list_metrics, metric_info
from .core.result import EvaluationResult, MetricResult
from .regression import (
    adjusted_r2,
    explained_variance,
    huber_loss,
    mae,
    mape,
    max_error,
    mean_bias_error,
    median_absolute_error,
    mse,
    msle,
    quantile_loss,
    r2,
    rae,
    rmse,
    rmsle,
    rse,
    smape,
)
from .version import __version__

__all__ = [
    "EvalSuiteError",
    "EvaluationResult",
    "InputValidationError",
    "MetricInfo",
    "MetricInputError",
    "MetricResult",
    "OptionalDependencyError",
    "StatisticalTestError",
    "UndefinedMetricWarning",
    "UnsupportedTaskError",
    "__version__",
    "accuracy",
    "adjusted_r2",
    "average_precision",
    "balanced_accuracy",
    "brier_score",
    "classification",
    "cohen_kappa",
    "confusion_matrix",
    "evaluate",
    "explained_variance",
    "f1",
    "fbeta",
    "hamming_loss",
    "huber_loss",
    "jaccard",
    "list_metrics",
    "log_loss",
    "mae",
    "mape",
    "max_error",
    "mcc",
    "mean_bias_error",
    "median_absolute_error",
    "metric_info",
    "mse",
    "msle",
    "npv",
    "pr_curve",
    "precision",
    "quantile_loss",
    "r2",
    "rae",
    "recall",
    "regression",
    "rmse",
    "rmsle",
    "roc_auc",
    "roc_curve",
    "rse",
    "smape",
    "specificity",
    "top_k_accuracy",
]
